-- tables
CREATE TABLE Ocena (
    IdOcena integer  NOT NULL,
    Przedmiot varchar2(64)  NOT NULL,
    Wartosc number(2,1)  NOT NULL,
    IdStudent integer  NOT NULL,
    CONSTRAINT Ocena_pk PRIMARY KEY (IdOcena)
) ;

CREATE TABLE Student (
    IdStudent integer  NOT NULL,
    Nazwisko varchar2(64)  NOT NULL,
    Rok integer  NOT NULL,
    CONSTRAINT Student_pk PRIMARY KEY (IdStudent)
) ;

-- foreign keys
ALTER TABLE Ocena ADD CONSTRAINT Ocena_Student
    FOREIGN KEY (IdStudent)
    REFERENCES Student (IdStudent);


INSERT INTO STUDENT VALUES(1,'KOWALSKI',1);
INSERT INTO STUDENT VALUES(2,'KWIATKOWSKA',1);
INSERT INTO STUDENT VALUES(3,'DOMARADZKA',1);
INSERT INTO STUDENT VALUES(4,'GUT',1);
INSERT INTO STUDENT VALUES(5,'NOWAK',1);
INSERT INTO STUDENT VALUES(6,'ADAMCZYK',2);
INSERT INTO STUDENT VALUES(7,'PAWŁOWSKI',2);
INSERT INTO STUDENT VALUES(8,'PACHUT',2);
INSERT INTO STUDENT VALUES(9,'WERNER',2);
INSERT INTO STUDENT VALUES(10,'PILA',2);

INSERT INTO OCENA VALUES(1,'RBD',3,1);
INSERT INTO OCENA VALUES(2,'SBD',3,1);
INSERT INTO OCENA VALUES(3,'AUG',3,1);
INSERT INTO OCENA VALUES(4,'RBD',4,2);
INSERT INTO OCENA VALUES(5,'SBD',5,2);
INSERT INTO OCENA VALUES(6,'AUG',3.5,2);
INSERT INTO OCENA VALUES(7,'RBD',4.5,3);
INSERT INTO OCENA VALUES(8,'SBD',5,3);
INSERT INTO OCENA VALUES(9,'AUG',4,3);
INSERT INTO OCENA VALUES(10,'RBD',2,4);
INSERT INTO OCENA VALUES(11,'SBD',2,4);
INSERT INTO OCENA VALUES(12,'AUG',3,4);
INSERT INTO OCENA VALUES(13,'RBD',5,5);
INSERT INTO OCENA VALUES(14,'SBD',5,5);
INSERT INTO OCENA VALUES(15,'AUG',5,5);
INSERT INTO OCENA VALUES(16,'PIP',3,6);
INSERT INTO OCENA VALUES(17,'ANG',2,6);
INSERT INTO OCENA VALUES(18,'UTP',2,6);
INSERT INTO OCENA VALUES(19,'PIP',4,7);
INSERT INTO OCENA VALUES(20,'ANG',4.5,7);
INSERT INTO OCENA VALUES(21,'UTP',5,7);
INSERT INTO OCENA VALUES(22,'PIP',3,8);
INSERT INTO OCENA VALUES(23,'ANG',4.5,8);
INSERT INTO OCENA VALUES(24,'UTP',3,8);
INSERT INTO OCENA VALUES(25,'PIP',2,9);
INSERT INTO OCENA VALUES(26,'ANG',2,9);
INSERT INTO OCENA VALUES(27,'UTP',3,9);
INSERT INTO OCENA VALUES(28,'PIP',5,10);
INSERT INTO OCENA VALUES(29,'ANG',4.5,10);
INSERT INTO OCENA VALUES(30,'UTP',3,10);
