--ZADANIE 1
CREATE TRIGGER tr1 ON EMP
FOR DELETE
AS
BEGIN
    PRINT('DO NOT DELETE EMPLOYEES');
    ROLLBACK;
END;

DELETE FROM EMP WHERE EMPNO=7950;

DROP TRIGGER tr1;

GO;


--ZADANIE 2
CREATE TRIGGER tr2 ON EMP
FOR INSERT
AS
BEGIN
    INSERT INTO EMP
    SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, ISNULL(COMM, 0), DEPTNO
    FROM INSERTED
    PRINT 'USTAWIONO PROWIZJE PRACOWNIKA NA 0';
END;

INSERT INTO EMP (EMPNO, ENAME, JOB, SAL)
VALUES (7951, 'NOWAK', 'SALESMAN', 5250);

DROP TRIGGER tr2;

GO;

--ZADANIE 3
CREATE TRIGGER tr3 ON EMP
FOR UPDATE , INSERT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM INSERTED WHERE SAL < 1000)
        BEGIN
            ROLLBACK;
            RAISERROR('SAL NIE MOZE BYC MNIEJSZE NIZ 1000', 1, 13);
        END;
END;

INSERT INTO EMP (EMPNO, ENAME, JOB, SAL)
VALUES (7952, 'POLAK', 'SALESMAN', 500);

DROP TRIGGER tr3;

GO;

--ZADANIE 4
CREATE TABLE budzet (wartosc INT NOT NULL);

INSERT INTO budzet (wartosc)
SELECT SUM(sal) FROM emp;


CREATE TRIGGER tr4 ON EMP
FOR INSERT, UPDATE, DELETE
AS
BEGIN
    UPDATE budzet SET wartosc = (SELECT SUM(sal) FROM emp);
END;

DROP TRIGGER tr4;

--ZADANIE 5
CREATE TRIGGER tr5
    ON DEPT
    FOR UPDATE
    AS
BEGIN
    IF (SELECT DNAME FROM INSERTED) IS NOT NULL
        BEGIN
            PRINT ('NIE MOZNA ZMIENIAC NAZWY DZIALU');
            ROLLBACK;
        END;
END;


UPDATE DEPT
SET DNAME = 'HR'
WHERE DEPTNO = 50;

INSERT INTO DEPT
VALUES (50, 'SUPPORT', 'WARSAW');

DROP TRIGGER tr5;

GO;

--ZADANIE 6
ALTER TRIGGER tr6
    ON EMP
    FOR INSERT, UPDATE, DELETE
    AS
BEGIN
        IF EXISTS (
            SELECT 1
            FROM DELETED
            INNER JOIN INSERTED ON INSERTED.EMPNO = DELETED.EMPNO
            WHERE SAL>0
            AND NOT EXISTS(SELECT)
            )
            BEGIN
                RAISERROR('NIE MOZNA USUNAC PRACOWNIKA Z PENSJA > 0', 2, 16);
                ROLLBACK TRANSACTION;
            END;

        IF EXISTS (
            SELECT 1
            FROM INSERTED
            INNER JOIN DELETED ON INSERTED.EMPNO = DELETED.EMPNO
            WHERE INSERTED.ENAME <> DELETED.ENAME
        )
            BEGIN
                RAISERROR('NIE MOZNA ZMIENIC NAZWISKA PRACOWNIKA', 3, 16);
                ROLLBACK TRANSACTION;
            END;

        IF EXISTS (
            SELECT 1
            FROM INSERTED
            INNER JOIN EMP ON EMP.EMPNO = INSERTED.EMPNO
        )
            BEGIN
                RAISERROR('PRACOWNIK O TYM NAZWISKU JUZ ISTNIEJE', 4, 16);
                ROLLBACK TRANSACTION;
            END;
END;

SELECT * FROM EMP;
DELETE FROM EMP WHERE EMPNO = 7951;
UPDATE EMP SET ENAME = 'NOWACKI' WHERE EMPNO = 7951;
INSERT INTO EMP (EMPNO, ENAME, SAL) VALUES (9999, 'NOWAK', 3000);

DROP TRIGGER tr6;

GO;

--ZADANIE 7
CREATE TRIGGER tr7 ON EMP
FOR UPDATE, DELETE
AS
BEGIN
    IF EXISTS (
        SELECT 1 FROM INSERTED
        INNER JOIN DELETED ON INSERTED.EMPNO = DELETED.EMPNO
        WHERE DELETED.SAL > INSERTED.SAL
    )
        BEGIN
            ROLLBACK;
            RAISERROR('NIE MOZNA ZMNIEJSZAC PENSJI PRACOWNIKA', 16, 5);
        END;

    IF EXISTS (
        SELECT 1 FROM DELETED

    )
        BEGIN
            ROLLBACK;
            RAISERROR('NIE MOZNA ZMNIEJSZAC PENSJI PRACOWNIKA', 16, 5);
        END;

END;

DROP TRIGGER tr7;