--ZADANIE 1
SELECT GOSC.NAZWISKO, GOSC.IMIE
FROM GOSC
ORDER BY NAZWISKO, IMIE;

--ZADANIE 2
SELECT DISTINCT GOSC.PROCENT_RABATU
FROM GOSC
ORDER BY GOSC.PROCENT_RABATU DESC;

--ZADANIE 3
SELECT REZERWACJA.IDREZERWACJA
FROM REZERWACJA
INNER JOIN GOSC ON REZERWACJA.IDGOSC = GOSC.IDGOSC
WHERE GOSC.IMIE = 'Ferdynand' AND GOSC.NAZWISKO = 'Kiepski';

--ZADANIE 4
SELECT GOSC.IMIE, GOSC.NAZWISKO, REZERWACJA.NRPOKOJU
FROM REZERWACJA
INNER JOIN GOSC ON REZERWACJA.IDGOSC = GOSC.IDGOSC
WHERE EXTRACT(YEAR FROM REZERWACJA.DATAOD) = 2008
AND (GOSC.NAZWISKO LIKE 'K%' OR GOSC.NAZWISKO LIKE 'L%');

--ZADANIE 5
SELECT REZERWACJA.NRPOKOJU
FROM REZERWACJA
INNER JOIN GOSC ON REZERWACJA.IDGOSC = GOSC.IDGOSC
WHERE GOSC.IMIE = 'Andrzej' AND GOSC.NAZWISKO = 'Nowak';

--ZADANIE 6
SELECT KATEGORIA.NAZWA, COUNT(POKOJ.NRPOKOJU)
FROM KATEGORIA
INNER JOIN POKOJ ON KATEGORIA.IDKATEGORIA = POKOJ.IDKATEGORIA
GROUP BY KATEGORIA.NAZWA;

--ZADANIE 7
SELECT GOSC.*, REZERWACJA.*
FROM GOSC
LEFT JOIN REZERWACJA ON GOSC.IDGOSC = REZERWACJA.IDGOSC;

--ZADANIE 8
SELECT GOSC.IDGOSC, GOSC.IMIE, GOSC.NAZWISKO
FROM GOSC
INNER JOIN REZERWACJA ON GOSC.IDGOSC = REZERWACJA.IDGOSC
WHERE REZERWACJA.NRPOKOJU = 101
AND REZERWACJA.ZAPLACONA = 1;

--ZADANIE 9
SELECT GOSC.NAZWISKO || GOSC.IMIE "NAZWISKO I IMIE", REZERWACJA.DATAOD, REZERWACJA.DATADO, REZERWACJA.NRPOKOJU, KATEGORIA.NAZWA KATEGORIA
FROM GOSC
INNER JOIN REZERWACJA ON GOSC.IDGOSC = REZERWACJA.IDGOSC
INNER JOIN POKOJ ON REZERWACJA.NRPOKOJU = POKOJ.NRPOKOJU
INNER JOIN KATEGORIA ON POKOJ.IDKATEGORIA = KATEGORIA.IDKATEGORIA;

--ZADANIE 10
SELECT GOSC.IDGOSC, GOSC.IMIE, GOSC.NAZWISKO, REZERWACJA.NRPOKOJU
FROM GOSC
INNER JOIN REZERWACJA ON GOSC.IDGOSC = REZERWACJA.IDGOSC
WHERE
REZERWACJA.NRPOKOJU = 101 AND GOSC.NAZWISKO LIKE 'K%'
OR
REZERWACJA.NRPOKOJU = 201 AND GOSC.NAZWISKO LIKE 'P%';

--ZADANIE 11
SELECT DISTINCT GOSC.IDGOSC, GOSC.IMIE, GOSC.NAZWISKO, GOSC.PROCENT_RABATU
FROM GOSC
RIGHT JOIN REZERWACJA ON GOSC.IDGOSC = REZERWACJA.IDGOSC
WHERE GOSC.PROCENT_RABATU IS NULL
AND REZERWACJA.IDGOSC IS NOT NULL;

--ZADANIE 12
SELECT REZERWACJA.*, GOSC.IMIE, GOSC.NAZWISKO, REZERWACJA.DATAOD
FROM REZERWACJA
INNER JOIN GOSC ON REZERWACJA.IDGOSC = GOSC.IDGOSC
WHERE REZERWACJA.NRPOKOJU IN (101,102,103,104);

--ZADANIE 13
SELECT KATEGORIA.NAZWA, KATEGORIA.CENA
FROM KATEGORIA
WHERE KATEGORIA.CENA BETWEEN 10 AND 100;

--ZADANIE 14
SELECT GOSC.NAZWISKO || GOSC.IMIE "DŁUŻNIK"
FROM GOSC
INNER JOIN REZERWACJA ON GOSC.IDGOSC = REZERWACJA.IDGOSC
WHERE REZERWACJA.ZAPLACONA = 0
ORDER BY GOSC.NAZWISKO, GOSC.IMIE;

--ZADANIE 15
SELECT COUNT(REZERWACJA.IDREZERWACJA) "ZAPLACONE REZERWACJE"
FROM REZERWACJA
WHERE REZERWACJA.ZAPLACONA = 1;

--ZADANIE 16
SELECT COUNT(REZERWACJA.IDREZERWACJA) "REZERWACJE W 2009"
FROM REZERWACJA
WHERE EXTRACT(YEAR FROM REZERWACJA.DATAOD) = 2009;

--ZADANIE 17
INSERT INTO GOSC VALUES (11, 'Maria', 'Fuks', 25);

--ZADANIE 18
UPDATE REZERWACJA
SET DATADO = '2009-07-07'
WHERE REZERWACJA.IDREZERWACJA = 1;

--ZADANIE 19
DELETE FROM REZERWACJA
WHERE REZERWACJA.IDREZERWACJA = 20;
