--ZADANIE 1
SELECT GOSC.IMIE, GOSC.NAZWISKO, COUNT(REZERWACJA.IDREZERWACJA) LICZBA_REZERWACJI
FROM GOSC
INNER JOIN REZERWACJA ON GOSC.IDGOSC = REZERWACJA.IDGOSC
GROUP BY GOSC.IMIE, GOSC.NAZWISKO
HAVING COUNT(REZERWACJA.IDREZERWACJA) <> 1;

--ZADANIE 2
SELECT POKOJ.NRPOKOJU
FROM POKOJ
WHERE LICZBA_MIEJSC = (
    SELECT MAX(POKOJ.LICZBA_MIEJSC)
    FROM POKOJ
    );

--ZADANIE 3
SELECT POKOJ.NRPOKOJU, MAX(REZERWACJA.DATADO)
FROM POKOJ
INNER JOIN REZERWACJA ON POKOJ.NRPOKOJU = REZERWACJA.NRPOKOJU
GROUP BY POKOJ.NRPOKOJU;

--ZADANIE 4
SELECT POKOJ.NRPOKOJU, COUNT(REZERWACJA.IDREZERWACJA) LICZBA_REZERWACJI
FROM POKOJ
INNER JOIN REZERWACJA ON POKOJ.NRPOKOJU = REZERWACJA.NRPOKOJU
INNER JOIN KATEGORIA ON POKOJ.IDKATEGORIA = KATEGORIA.IDKATEGORIA
WHERE KATEGORIA.NAZWA NOT LIKE 'Luksusowy'
GROUP BY POKOJ.NRPOKOJU
HAVING COUNT(REZERWACJA.IDREZERWACJA) <> 1;

--ZADANIE 5
SELECT GOSC.IMIE, GOSC.NAZWISKO, POKOJ.NRPOKOJU
FROM GOSC
INNER JOIN REZERWACJA ON GOSC.IDGOSC = REZERWACJA.IDGOSC
INNER JOIN POKOJ ON REZERWACJA.NRPOKOJU = POKOJ.NRPOKOJU
WHERE REZERWACJA.DATAOD = (
    SELECT MAX(REZERWACJA.DATAOD)
    FROM REZERWACJA
    );

--ZADANIE 6
SELECT POKOJ.NRPOKOJU, POKOJ.IDKATEGORIA, POKOJ.LICZBA_MIEJSC
FROM POKOJ
WHERE NOT EXISTS(
    SELECT REZERWACJA.NRPOKOJU
    FROM REZERWACJA
    WHERE REZERWACJA.NRPOKOJU = POKOJ.NRPOKOJU
);

--ZADANIE 7
SELECT GOSC.IMIE, GOSC.NAZWISKO
FROM GOSC
WHERE NOT EXISTS(
    SELECT g2.IMIE,g2.NAZWISKO
    FROM GOSC g2
    INNER JOIN REZERWACJA ON GOSC.IDGOSC = REZERWACJA.IDGOSC
    INNER JOIN POKOJ ON REZERWACJA.NRPOKOJU = POKOJ.NRPOKOJU
    INNER JOIN KATEGORIA ON POKOJ.IDKATEGORIA = KATEGORIA.IDKATEGORIA
    WHERE KATEGORIA.NAZWA NOT LIKE 'Luksusowy'
);

--ZADANIE 8
SELECT GOSC.IMIE, GOSC.NAZWISKO, NVL(TO_CHAR(REZERWACJA.DATAOD), 'BRAK') AS DATA_REZERWACJI
FROM GOSC
INNER JOIN REZERWACJA ON GOSC.IDGOSC = REZERWACJA.IDGOSC
WHERE REZERWACJA.NRPOKOJU = 101

UNION

SELECT GOSC.IMIE, GOSC.NAZWISKO, 'BRAK'
FROM GOSC
LEFT JOIN REZERWACJA ON GOSC.IDGOSC = REZERWACJA.IDGOSC
WHERE REZERWACJA.IDREZERWACJA IS NULL;

--ZADANIE 9
SELECT KATEGORIA.NAZWA, COUNT(POKOJ.NRPOKOJU) AS LICZBA_POKOI
FROM KATEGORIA
INNER JOIN POKOJ ON KATEGORIA.IDKATEGORIA = POKOJ.IDKATEGORIA
HAVING COUNT(POKOJ.NRPOKOJU) = (
    SELECT MAX(COUNT(POKOJ.NRPOKOJU))
    FROM KATEGORIA
    INNER JOIN POKOJ ON KATEGORIA.IDKATEGORIA = POKOJ.IDKATEGORIA
    GROUP BY KATEGORIA.NAZWA
    )
GROUP BY KATEGORIA.NAZWA;

--ZADANIE 10
SELECT KATEGORIA.NAZWA, MAX(POKOJ.LICZBA_MIEJSC)
FROM KATEGORIA
INNER JOIN POKOJ ON KATEGORIA.IDKATEGORIA = POKOJ.IDKATEGORIA
GROUP BY KATEGORIA.NAZWA;

